name: Version 12

on:
  pull_request:
    branches:
      - main
    paths:
      - images/production/**
      - .github/workflows/build_version_12.yaml
      - .github/workflows/reuse_build_push.yaml
      - resources/**

  schedule:
    # Every day at 12:00 pm
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  v14:
    uses: ./.github/workflows/reuse_build_push.yml
    with:
      version: "12"
      build_args: |
        FRAPPE_BRANCH=version-12
        ERPNEXT_BRANCH=version-12
        PYTHON_VERSION=3.7.16
        NODE_VERSION=12.22.12
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
